// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlwgCFrkVztA60AIE-PJcMAoK-Ads3Qj4',
    appId: '1:737590269295:web:d1dcae0ee55964e085c49a',
    messagingSenderId: '737590269295',
    projectId: 'weather-station-esp32-bc66b',
    authDomain: 'weather-station-esp32-bc66b.firebaseapp.com',
    storageBucket: 'weather-station-esp32-bc66b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDymqNApZVew0dKOgyywFlt1VbPnGqSoMc',
    appId: '1:737590269295:android:50712fd9d3a0633985c49a',
    messagingSenderId: '737590269295',
    projectId: 'weather-station-esp32-bc66b',
    storageBucket: 'weather-station-esp32-bc66b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEeCJVjSbEyu40mDolW8aM3iMjx947jJs',
    appId: '1:737590269295:ios:a7c12bee3fda5fc085c49a',
    messagingSenderId: '737590269295',
    projectId: 'weather-station-esp32-bc66b',
    storageBucket: 'weather-station-esp32-bc66b.appspot.com',
    iosClientId: '737590269295-avnlp24e630fm76tfjkssuplo8jfm04s.apps.googleusercontent.com',
    iosBundleId: 'com.example.weatherStationEsp32',
  );
}
